// Generated by https://quicktype.io

using System.Text.Json.Serialization;

namespace MarcusTurewicz.Gävlebocken
{
    public class TweetObject
    {
        [JsonPropertyName("id")]
        public long Id { get; set; }

        [JsonPropertyName("text")]
        public string Text { get; set; }

    }
}